# Generated by Django 3.2.5 on 2021-07-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_botusers_user_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='botusers',
            name='user_lang',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
