# Generated by Django 3.2.5 on 2021-07-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_botusers_user_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='botusers',
            name='user_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
