# Generated by Django 3.2.5 on 2021-08-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_botusers_user_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='botusers',
            name='translate_from_lang',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='botusers',
            name='translate_to_lang',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
